backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "dogs"
    label: "Nasze psy"
    folder: "src/pages"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: "officialName"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "our-dogs"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Zdjęcie główne", name: image, widget: image, required: false}
      - {label: "Nazwa", name: "officialName", widget: "string"}
      - {label: "Rodowód", name: "lineage", widget: "string"}
      - {label: "Imię domowe", name: "homeName", widget: "string", required: false}
      - {label: "Płeć", name: "gender", widget: "select", options: [{ label: "Pies", value: "male" }, { label: "Suka", value: "female" }, {label: 'Weteran', value: "veteran"}]}
      - {label: "Data urodzenia", name: "birthDate", widget: "date", default: "", required: false}
      - {label: "Osiągnięcia", name: "achievements", widget: list}
      - {label: "Galeria", name: "galleryImages", widget: list, fields: [{label: Image, name: image, widget: image, required: false}, {required: false, default: "", label: "Podpis", name: "description", widget: string}]}
      - {label: "Opis", name: "description", widget: "text", required: false}
