backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "dogs"
    label: "Nasze psy"
    folder: "src/pages"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: "officialName"
    filter: {field: "templateKey", value: "our-dogs"}
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "our-dogs"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Zdjęcie główne", name: image, widget: image, required: false}
      - {label: "Nazwa", name: "officialName", widget: "string"}
      - {label: "Rodowód", name: "lineage", widget: "string"}
      - {label: "Imię domowe", name: "homeName", widget: "string", required: false}
      - {label: "Płeć", name: "gender", widget: "select", options: [{ label: "Pies", value: "male" }, { label: "Suka", value: "female" }, {label: 'Weteran', value: "veteran"}]}
      - {label: "Data urodzenia", name: "birthDate", widget: "date", default: "", required: false}
      - {label: "Osiągnięcia", name: "achievements", widget: list}
      - {label: "Galeria", name: "galleryImages", widget: list, fields: [{label: Image, name: image, widget: image, required: false}, {required: false, default: "", label: "Podpis", name: "description", widget: string}]}
      - {label: "Opis", name: "description", widget: "text", required: false}

  - name: "litters"
    label: "Szczenięta"
    folder: "src/pages"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter: {field: "templateKey", value: "our-litters"}
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "our-litters"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Nazwa miotu", name: "title", widget: "string"}
      - {label: "Zdjęcie główne", name: image, widget: image, required: false}
      - {label: "Data urodzenia", name: "birthDate", widget: "date", default: "", required: false}
      - {label: "Rodzice", name: "parents", widget: object, fields: [{default: "", label: "Ojciec", name: "father", widget: string}, {default: "", label: "Matka", name: "mother", widget: string}]}
      - {label: "Szczenięta", name: "puppies", widget: list, fields: [{default: "", label: "Imię", name: "name", widget: string, required: false}, {default: false, label: "Na sprzedaż", name: "available", widget: boolean, required: false}, {label: "Płeć", name: "gender", widget: "select", options: [{ label: "Pies", value: "male" }, { label: "Suka", value: "female" }]}]}
      - {label: "Galeria", name: "galleryImages", widget: list,  fields: [{label: Image, name: image, widget: image, required: false}, {default: "", label: "Podpis", name: "description", widget: string, required: false}]}

  - name: "exhibitions"
    label: "Wystawy"
    folder: "src/pages"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: "officialName"
    filter: {field: "templateKey", value: "exhibitions"}
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "exhibitions"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Nazwa wystawy", name: "title", widget: "string"}
      - {label: "Zdjęcie główne", name: image, widget: image, required: false}
      - {label: "Data wystawy", name: "exhibitionDate", widget: "date", required: false}
      - {label: "Galeria", name: "galleryImages", widget: list, fields: [{label: Image, name: image, widget: image, required: false}, {required: false, default: "", label: "Podpis", name: "description", widget: string}]}
      - {label: "Wystawione psy", name: "dogs", widget: list, fields: [{label: "Pies", name: "dog", widget: string, required: false}, {required: false, default: [""], label: "Osiągnięcia", name: "achievements", widget: list}]}

  - name: "gallery"
    label: "Galeria"
    folder: "src/pages"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter: {field: "templateKey", value: "gallery"}
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "gallery"}
      - {label: "Nazwa folderu", name: "title", widget: "string"}
      - {label: "Zdjęcia", name: "galleryImages", widget: list,  fields: [{label: Image, name: image, widget: image}, {required: false, default: "", label: "Podpis", name: "description", widget: string}]}
